"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 18:08:28.516487
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_story_clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("representative_article_id", sa.BigInteger(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("independent_source_count", sa.Integer(), nullable=False),
        sa.Column("language_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("name_ar", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_emerging", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "daily_metrics",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("articles", sa.Integer(), nullable=False),
        sa.Column("unique_stories", sa.Integer(), nullable=False),
        sa.Column("sources_active", sa.Integer(), nullable=False),
        sa.Column("duplicate_rate", sa.Float(), nullable=True),
        sa.Column("language_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("group_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sentiment_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("topic_entropy", sa.Float(), nullable=True),
        sa.Column("source_diversity", sa.Float(), nullable=True),
        sa.Column("language_diversity", sa.Float(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "daily_summaries",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("day", "language"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("subtype", sa.String(length=60), nullable=True),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("name_ar", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("wikidata_id", sa.String(length=20), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("is_public_figure", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False)
    op.create_table(
        "frames",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("discovered", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "global_topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label_en", sa.Text(), nullable=False),
        sa.Column("label_ar", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("centroid", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "languages",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name_en", sa.String(length=80), nullable=False),
        sa.Column("name_native", sa.String(length=80), nullable=True),
        sa.Column("script", sa.String(length=20), nullable=False),
        sa.Column("rtl", sa.Boolean(), nullable=False),
        sa.Column("supported", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("license", sa.String(length=80), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_type", sa.String(length=30), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=True),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("json_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_native", sa.String(length=200), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_group", sa.String(length=60), nullable=False),
        sa.Column("geographic_focus", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("yemen_coverage", sa.String(length=20), nullable=True),
        sa.Column("operating_base", sa.String(length=30), nullable=False),
        sa.Column("ownership_description", sa.Text(), nullable=True),
        sa.Column("ownership_evidence_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("access_policy", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_sources_country"), "sources", ["country"], unique=False)
    op.create_index(op.f("ix_sources_domain"), "sources", ["domain"], unique=False)
    op.create_index(op.f("ix_sources_operating_base"), "sources", ["operating_base"], unique=False)
    op.create_index(op.f("ix_sources_source_group"), "sources", ["source_group"], unique=False)
    op.create_table(
        "topic_metrics",
        sa.Column("dimension", sa.String(length=10), nullable=False),
        sa.Column("ref_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("story_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("language_count", sa.Integer(), nullable=False),
        sa.Column("mean_sentiment", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("dimension", "ref_id", "day"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("api_key_hash", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "drift_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drift_reports_day"), "drift_reports", ["day"], unique=False)
    op.create_table(
        "entity_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("surface_form", sa.String(length=300), nullable=False),
        sa.Column("normalized_form", sa.String(length=300), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("alias_type", sa.String(length=30), nullable=False),
        sa.Column("framing_note", sa.Text(), nullable=True),
        sa.Column("match", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "normalized_form", "language"),
    )
    op.create_index(op.f("ix_entity_aliases_entity_id"), "entity_aliases", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_entity_aliases_normalized_form"), "entity_aliases", ["normalized_form"], unique=False
    )
    op.create_table(
        "entity_metrics",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("mean_targeted_sentiment", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entity_id", "day"),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("prompt_template_id", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_template_id"],
            ["prompt_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prompt_template_id", "input_hash", "model"),
    )
    op.create_index(op.f("ix_llm_calls_input_hash"), "llm_calls", ["input_hash"], unique=False)
    op.create_index(
        op.f("ix_llm_calls_prompt_template_id"), "llm_calls", ["prompt_template_id"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("location_type", sa.String(length=30), nullable=False),
        sa.Column("governorate_entity_id", sa.Integer(), nullable=True),
        sa.Column("admin_code", sa.String(length=20), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["governorate_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "model_languages",
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("model_id", "language_code"),
    )
    op.create_table(
        "model_tasks",
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("task", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("model_id", "task"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "version"),
    )
    op.create_index(op.f("ix_model_versions_model_id"), "model_versions", ["model_id"], unique=False)
    op.create_table(
        "saved_queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("article_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_queries_user_id"), "saved_queries", ["user_id"], unique=False)
    op.create_table(
        "source_feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("feed_type", sa.String(length=30), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.Date(), nullable=True),
        sa.Column("yemen_filter", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column("last_item_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_source_feeds_source_id"), "source_feeds", ["source_id"], unique=False)
    op.create_table(
        "source_languages",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_code"],
            ["languages.code"],
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "language_code"),
    )
    op.create_table(
        "source_metrics",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("mean_sentiment", sa.Float(), nullable=True),
        sa.Column("category_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "day"),
    )
    op.create_table(
        "source_orientation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("simplified", sa.String(length=40), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("last_reviewed", sa.Date(), nullable=True),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_orientation_source_id"), "source_orientation", ["source_id"], unique=False
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("publisher_name", sa.String(length=300), nullable=True),
        sa.Column("publisher_domain", sa.String(length=200), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at_estimated", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("excerpt_normalized", sa.Text(), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("language_confidence", sa.Float(), nullable=True),
        sa.Column("script", sa.String(length=20), nullable=True),
        sa.Column("is_mixed_language", sa.Boolean(), nullable=False),
        sa.Column("translated_title", sa.Text(), nullable=True),
        sa.Column("translation_status", sa.String(length=20), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("yemen_relevance", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("quality_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duplicate_of_id", sa.BigInteger(), nullable=True),
        sa.Column("canonical_article_id", sa.BigInteger(), nullable=True),
        sa.Column("story_cluster_id", sa.Integer(), nullable=True),
        sa.Column("syndication_cluster_id", sa.Integer(), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("is_syndicated", sa.Boolean(), nullable=False),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("analysed_content_hash", sa.String(length=64), nullable=True),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('simple', coalesce(title_normalized, '')), 'A') || setweight(to_tsvector('simple', coalesce(excerpt_normalized, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["canonical_article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["source_feeds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_cluster_id"],
            ["article_story_clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_hash"),
    )
    op.create_index(op.f("ix_articles_content_hash"), "articles", ["content_hash"], unique=False)
    op.create_index(op.f("ix_articles_duplicate_of_id"), "articles", ["duplicate_of_id"], unique=False)
    op.create_index(op.f("ix_articles_language"), "articles", ["language"], unique=False)
    op.create_index(op.f("ix_articles_processing_status"), "articles", ["processing_status"], unique=False)
    op.create_index(op.f("ix_articles_published_at"), "articles", ["published_at"], unique=False)
    op.create_index(op.f("ix_articles_publisher_domain"), "articles", ["publisher_domain"], unique=False)
    op.create_index(
        "ix_articles_search_tsv", "articles", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_articles_source_id"), "articles", ["source_id"], unique=False)
    op.create_index("ix_articles_source_published", "articles", ["source_id", "published_at"], unique=False)
    op.create_index(op.f("ix_articles_story_cluster_id"), "articles", ["story_cluster_id"], unique=False)
    op.create_index(
        op.f("ix_articles_syndication_cluster_id"), "articles", ["syndication_cluster_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("location_entity_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("report_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_type", "event_date", "location_entity_id"),
    )
    op.create_index(op.f("ix_events_event_date"), "events", ["event_date"], unique=False)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_location_entity_id"), "events", ["location_entity_id"], unique=False)
    op.create_table(
        "model_benchmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("task", sa.String(length=40), nullable=False),
        sa.Column("dataset", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("metric", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_benchmarks_model_version_id"), "model_benchmarks", ["model_version_id"], unique=False
    )
    op.create_table(
        "pipeline_errors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("feed_id", sa.Integer(), nullable=True),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("error_type", sa.String(length=80), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["source_feeds.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_errors_run_id"), "pipeline_errors", ["run_id"], unique=False)
    op.create_index(op.f("ix_pipeline_errors_source_id"), "pipeline_errors", ["source_id"], unique=False)
    op.create_table(
        "source_orientation_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("orientation_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("evidence_type", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("accessed_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["orientation_id"], ["source_orientation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_orientation_evidence_orientation_id"),
        "source_orientation_evidence",
        ["orientation_id"],
        unique=False,
    )
    op.create_table(
        "terminology_variants",
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["alias_id"], ["entity_aliases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias_id", "source_id", "day"),
    )
    op.create_index(
        op.f("ix_terminology_variants_entity_id"), "terminology_variants", ["entity_id"], unique=False
    )
    op.create_table(
        "topic_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("algorithm", sa.String(length=40), nullable=False),
        sa.Column("embedding_model_version_id", sa.Integer(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("training_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("training_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["embedding_model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("original_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corrected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annotations_article_id"), "annotations", ["article_id"], unique=False)
    op.create_index(op.f("ix_annotations_user_id"), "annotations", ["user_id"], unique=False)
    op.create_table(
        "article_duplicates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("from_article_id", sa.BigInteger(), nullable=False),
        sa.Column("to_article_id", sa.BigInteger(), nullable=False),
        sa.Column("relation_type", sa.String(length=30), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["from_article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(["to_article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_article_id", "to_article_id", "relation_type"),
    )
    op.create_index(
        op.f("ix_article_duplicates_from_article_id"), "article_duplicates", ["from_article_id"], unique=False
    )
    op.create_index(
        op.f("ix_article_duplicates_to_article_id"), "article_duplicates", ["to_article_id"], unique=False
    )
    op.create_table(
        "article_embeddings",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "model_version_id"),
    )
    op.create_table(
        "article_sources",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feed_id"], ["source_feeds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "feed_id"),
    )
    op.create_table(
        "article_versions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_article_versions_article_id"), "article_versions", ["article_id"], unique=False)
    op.create_table(
        "category_assignments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(length=12), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("route", sa.String(length=20), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_category_assignments_article_id"), "category_assignments", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_category_assignments_category_id"), "category_assignments", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_category_assignments_is_current"), "category_assignments", ["is_current"], unique=False
    )
    op.create_index(
        op.f("ix_category_assignments_model_version_id"),
        "category_assignments",
        ["model_version_id"],
        unique=False,
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("claimant_entity_id", sa.Integer(), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("fact_check_url", sa.Text(), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["claimant_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_article_id"), "claims", ["article_id"], unique=False)
    op.create_table(
        "emotion_analysis",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dominant", sa.String(length=40), nullable=True),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emotion_analysis_article_id"), "emotion_analysis", ["article_id"], unique=False)
    op.create_index(op.f("ix_emotion_analysis_is_current"), "emotion_analysis", ["is_current"], unique=False)
    op.create_index(
        op.f("ix_emotion_analysis_model_version_id"), "emotion_analysis", ["model_version_id"], unique=False
    )
    op.create_table(
        "entity_mentions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("alias_id", sa.Integer(), nullable=True),
        sa.Column("surface_form", sa.String(length=300), nullable=False),
        sa.Column("ner_label", sa.String(length=20), nullable=True),
        sa.Column("field", sa.String(length=10), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("sentence", sa.Text(), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["alias_id"],
            ["entity_aliases.id"],
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_mentions_alias_id"), "entity_mentions", ["alias_id"], unique=False)
    op.create_index(op.f("ix_entity_mentions_article_id"), "entity_mentions", ["article_id"], unique=False)
    op.create_index(op.f("ix_entity_mentions_entity_id"), "entity_mentions", ["entity_id"], unique=False)
    op.create_table(
        "event_actors",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "entity_id"),
    )
    op.create_table(
        "event_mentions",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_sentence", sa.Text(), nullable=True),
        sa.Column("trigger", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "article_id"),
    )
    op.create_table(
        "framing_analysis",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("frame_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("evidence_sentence", sa.Text(), nullable=True),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["frame_id"],
            ["frames.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_framing_analysis_article_id"), "framing_analysis", ["article_id"], unique=False)
    op.create_index(op.f("ix_framing_analysis_frame_id"), "framing_analysis", ["frame_id"], unique=False)
    op.create_index(op.f("ix_framing_analysis_is_current"), "framing_analysis", ["is_current"], unique=False)
    op.create_index(
        op.f("ix_framing_analysis_model_version_id"), "framing_analysis", ["model_version_id"], unique=False
    )
    op.create_table(
        "sentiment_analysis",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("polarity", sa.String(length=10), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("intensity", sa.Float(), nullable=True),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sentiment_analysis_article_id"), "sentiment_analysis", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_sentiment_analysis_is_current"), "sentiment_analysis", ["is_current"], unique=False
    )
    op.create_index(
        op.f("ix_sentiment_analysis_model_version_id"),
        "sentiment_analysis",
        ["model_version_id"],
        unique=False,
    )
    op.create_table(
        "targeted_sentiment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.String(length=10), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("evidence_sentence", sa.Text(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_targeted_sentiment_article_id"), "targeted_sentiment", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_targeted_sentiment_entity_id"), "targeted_sentiment", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_targeted_sentiment_is_current"), "targeted_sentiment", ["is_current"], unique=False
    )
    op.create_index(
        op.f("ix_targeted_sentiment_model_version_id"),
        "targeted_sentiment",
        ["model_version_id"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_model_id", sa.Integer(), nullable=False),
        sa.Column("topic_index", sa.Integer(), nullable=False),
        sa.Column("raw_representation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("label_method", sa.String(length=20), nullable=False),
        sa.Column("llm_description", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("parent_topic_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("language_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("representative_article_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("centroid", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(["topic_model_id"], ["topic_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_model_id", "topic_index"),
    )
    op.create_index(op.f("ix_topics_topic_model_id"), "topics", ["topic_model_id"], unique=False)
    op.create_table(
        "topic_alignments",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("global_topic_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["global_topic_id"], ["global_topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "global_topic_id"),
    )
    op.create_table(
        "topic_assignments",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("topic_model_id", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_model_id"], ["topic_models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "topic_id"),
    )
    op.create_index(
        op.f("ix_topic_assignments_topic_model_id"), "topic_assignments", ["topic_model_id"], unique=False
    )
    op.create_table(
        "topic_translations",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "language"),
    )
    # ### end Alembic commands ###
    op.create_foreign_key(
        "fk_story_cluster_representative",
        "article_story_clusters",
        "articles",
        ["representative_article_id"],
        ["id"],
    )
    op.create_index("ix_sources_is_demo", "sources", ["is_demo"])
    op.create_index("ix_articles_is_demo", "articles", ["is_demo"])
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_article_embeddings_hnsw ON article_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_article_embeddings_hnsw")
    op.drop_index("ix_articles_is_demo", table_name="articles")
    op.drop_constraint("fk_story_cluster_representative", "article_story_clusters", type_="foreignkey")
    op.drop_index("ix_sources_is_demo", table_name="sources")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topic_translations")
    op.drop_index(op.f("ix_topic_assignments_topic_model_id"), table_name="topic_assignments")
    op.drop_table("topic_assignments")
    op.drop_table("topic_alignments")
    op.drop_index(op.f("ix_topics_topic_model_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_targeted_sentiment_model_version_id"), table_name="targeted_sentiment")
    op.drop_index(op.f("ix_targeted_sentiment_is_current"), table_name="targeted_sentiment")
    op.drop_index(op.f("ix_targeted_sentiment_entity_id"), table_name="targeted_sentiment")
    op.drop_index(op.f("ix_targeted_sentiment_article_id"), table_name="targeted_sentiment")
    op.drop_table("targeted_sentiment")
    op.drop_index(op.f("ix_sentiment_analysis_model_version_id"), table_name="sentiment_analysis")
    op.drop_index(op.f("ix_sentiment_analysis_is_current"), table_name="sentiment_analysis")
    op.drop_index(op.f("ix_sentiment_analysis_article_id"), table_name="sentiment_analysis")
    op.drop_table("sentiment_analysis")
    op.drop_index(op.f("ix_framing_analysis_model_version_id"), table_name="framing_analysis")
    op.drop_index(op.f("ix_framing_analysis_is_current"), table_name="framing_analysis")
    op.drop_index(op.f("ix_framing_analysis_frame_id"), table_name="framing_analysis")
    op.drop_index(op.f("ix_framing_analysis_article_id"), table_name="framing_analysis")
    op.drop_table("framing_analysis")
    op.drop_table("event_mentions")
    op.drop_table("event_actors")
    op.drop_index(op.f("ix_entity_mentions_entity_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_article_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_alias_id"), table_name="entity_mentions")
    op.drop_table("entity_mentions")
    op.drop_index(op.f("ix_emotion_analysis_model_version_id"), table_name="emotion_analysis")
    op.drop_index(op.f("ix_emotion_analysis_is_current"), table_name="emotion_analysis")
    op.drop_index(op.f("ix_emotion_analysis_article_id"), table_name="emotion_analysis")
    op.drop_table("emotion_analysis")
    op.drop_index(op.f("ix_claims_article_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_category_assignments_model_version_id"), table_name="category_assignments")
    op.drop_index(op.f("ix_category_assignments_is_current"), table_name="category_assignments")
    op.drop_index(op.f("ix_category_assignments_category_id"), table_name="category_assignments")
    op.drop_index(op.f("ix_category_assignments_article_id"), table_name="category_assignments")
    op.drop_table("category_assignments")
    op.drop_index(op.f("ix_article_versions_article_id"), table_name="article_versions")
    op.drop_table("article_versions")
    op.drop_table("article_sources")
    op.drop_table("article_embeddings")
    op.drop_index(op.f("ix_article_duplicates_to_article_id"), table_name="article_duplicates")
    op.drop_index(op.f("ix_article_duplicates_from_article_id"), table_name="article_duplicates")
    op.drop_table("article_duplicates")
    op.drop_index(op.f("ix_annotations_user_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_article_id"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_table("topic_models")
    op.drop_index(op.f("ix_terminology_variants_entity_id"), table_name="terminology_variants")
    op.drop_table("terminology_variants")
    op.drop_index(
        op.f("ix_source_orientation_evidence_orientation_id"), table_name="source_orientation_evidence"
    )
    op.drop_table("source_orientation_evidence")
    op.drop_index(op.f("ix_pipeline_errors_source_id"), table_name="pipeline_errors")
    op.drop_index(op.f("ix_pipeline_errors_run_id"), table_name="pipeline_errors")
    op.drop_table("pipeline_errors")
    op.drop_index(op.f("ix_model_benchmarks_model_version_id"), table_name="model_benchmarks")
    op.drop_table("model_benchmarks")
    op.drop_index(op.f("ix_events_location_entity_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_event_date"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_articles_syndication_cluster_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_story_cluster_id"), table_name="articles")
    op.drop_index("ix_articles_source_published", table_name="articles")
    op.drop_index(op.f("ix_articles_source_id"), table_name="articles")
    op.drop_index("ix_articles_search_tsv", table_name="articles", postgresql_using="gin")
    op.drop_index(op.f("ix_articles_publisher_domain"), table_name="articles")
    op.drop_index(op.f("ix_articles_published_at"), table_name="articles")
    op.drop_index(op.f("ix_articles_processing_status"), table_name="articles")
    op.drop_index(op.f("ix_articles_language"), table_name="articles")
    op.drop_index(op.f("ix_articles_duplicate_of_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_content_hash"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_source_orientation_source_id"), table_name="source_orientation")
    op.drop_table("source_orientation")
    op.drop_table("source_metrics")
    op.drop_table("source_languages")
    op.drop_index(op.f("ix_source_feeds_source_id"), table_name="source_feeds")
    op.drop_table("source_feeds")
    op.drop_index(op.f("ix_saved_queries_user_id"), table_name="saved_queries")
    op.drop_table("saved_queries")
    op.drop_index(op.f("ix_model_versions_model_id"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_table("model_tasks")
    op.drop_table("model_languages")
    op.drop_table("locations")
    op.drop_index(op.f("ix_llm_calls_prompt_template_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_input_hash"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_table("entity_metrics")
    op.drop_index(op.f("ix_entity_aliases_normalized_form"), table_name="entity_aliases")
    op.drop_index(op.f("ix_entity_aliases_entity_id"), table_name="entity_aliases")
    op.drop_table("entity_aliases")
    op.drop_index(op.f("ix_drift_reports_day"), table_name="drift_reports")
    op.drop_table("drift_reports")
    op.drop_table("users")
    op.drop_table("topic_metrics")
    op.drop_index(op.f("ix_sources_source_group"), table_name="sources")
    op.drop_index(op.f("ix_sources_operating_base"), table_name="sources")
    op.drop_index(op.f("ix_sources_domain"), table_name="sources")
    op.drop_index(op.f("ix_sources_country"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("prompt_templates")
    op.drop_table("pipeline_runs")
    op.drop_table("models")
    op.drop_table("languages")
    op.drop_table("global_topics")
    op.drop_table("frames")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("daily_summaries")
    op.drop_table("daily_metrics")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_table("article_story_clusters")
    # ### end Alembic commands ###
